#!/bin/bash

set -e

mkdir -p "${HOME}/.ssh"

cat >"${HOME}/.ssh/deploy-key" <<.a
$DEPLOYKEY
.a

cat >"${HOME}/.ssh/config" <<.b
Host github.com
 HostName github.com
 IdentityFile ~/.ssh/deploy-key
.b

chmod 0600 "${HOME}/.ssh/config"
chmod 0600 "${HOME}/.ssh/deploy-key"

REPO_SSH="$(git remote get-url origin | sed 's|https://.*@github.com/|git@github.com:|')"
git remote set-url origin --push "${REPO_SSH}"

export GIT_COMMITTER_NAME="$(git log -1 --format='format:%an')"
export GIT_COMMITTER_EMAIL="$(git log -1 --format='format:%ae')"

GIT_EDITOR=cat git commit --amend
git push -f origin
